let dataJson = {
	version: "16.2.6",
	name: "",
	docProps: {
		docPropsCore: {created: "2024-03-14T03:03:34Z", creator: "Apache POI"},
		docPropsApp: {Application: "Apache POI"},
	},
	sheetCount: 1,
	tabStripRatio: 0.6,
	customList: [],
	activeSheetIndex: 0,
	sheets: {
		"ESG模仿界面1（ESG01）": {
			name: "ESG模仿界面1（ESG01）",
			isSelected: true,
			rowCount: 16,
			columnCount: 12,
			visible: 1,
			theme: "Office",
			data: {
				dataTable: {
					0: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "", style: "__builtInStyle2"},
						2: {value: "", style: "__builtInStyle2"},
						3: {value: "", style: "__builtInStyle2"},
						4: {value: "", style: "__builtInStyle2"},
						5: {value: "", style: "__builtInStyle2"},
						6: {value: "", style: "__builtInStyle2"},
						7: {value: "", style: "__builtInStyle2"},
						8: {value: "", style: "__builtInStyle2"},
						9: {value: "", style: "__builtInStyle2"},
						10: {value: "", style: "__builtInStyle2"},
						11: {value: "", style: "__builtInStyle2"},
					},
					1: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "", style: "__builtInStyle2"},
						2: {value: "", style: "__builtInStyle2"},
						3: {value: "", style: "__builtInStyle2"},
						4: {value: "", style: "__builtInStyle2"},
						5: {value: "", style: "__builtInStyle2"},
						6: {value: "", style: "__builtInStyle2"},
						7: {value: "", style: "__builtInStyle2"},
						8: {value: "", style: "__builtInStyle2"},
						9: {value: "", style: "__builtInStyle2"},
						10: {value: "", style: "__builtInStyle2"},
						11: {value: "", style: "__builtInStyle2"},
					},
					2: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "", style: "__builtInStyle3"},
						2: {value: "", style: "__builtInStyle3"},
						3: {value: "", style: "__builtInStyle3"},
						4: {value: "", style: "__builtInStyle3"},
						5: {value: "", style: "__builtInStyle3"},
						6: {value: "", style: "__builtInStyle3"},
						7: {value: "", style: "__builtInStyle3"},
						8: {value: "", style: "__builtInStyle3"},
						9: {value: "", style: "__builtInStyle3"},
						10: {value: "", style: "__builtInStyle3"},
						11: {value: "", style: "__builtInStyle3"},
					},
					3: {
						0: {value: "", style: "__builtInStyle4"},
						1: {value: "Start\nDate", style: "__builtInStyle5"},
						2: {value: "End\nDate", style: "__builtInStyle5"},
						3: {value: "Duration\n(No. of Days)", style: "__builtInStyle5"},
						4: {value: "Parent\nLocation", style: "__builtInStyle5"},
						5: {value: "Consumer", style: "__builtInStyle5"},
						6: {value: "GHG Protocol\nScope", style: "__builtInStyle5"},
						7: {value: "Provider", style: "__builtInStyle5"},
						8: {value: "Cost", style: "__builtInStyle5"},
						9: {value: "Consumption\n(kWh)", style: "__builtInStyle5"},
						10: {value: "GHG\nEmission(kg)", style: "__builtInStyle5"},
						11: {value: "Bill", style: "__builtInStyle5"},
					},
					4: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "/OADate(44105)/", style: "__builtInStyle6"},
						2: {value: "/OADate(44196)/", style: "__builtInStyle6"},
						3: {value: 92, style: "__builtInStyle7"},
						4: {value: "Manufaturing", style: "__builtInStyle7"},
						5: {value: "Manufaturing\nPlant C", style: "__builtInStyle7"},
						6: {value: 2, style: "__builtInStyle7"},
						7: {value: "Camron\nWilliamon", style: "__builtInStyle7"},
						8: {value: 8538.16, style: "__builtInStyle7"},
						9: {value: 6314.001, style: "__builtInStyle7"},
						10: {value: 1906.2, style: "__builtInStyle7"},
						11: {value: "202012.pdf\nUpload New", style: "__builtInStyle8"},
					},
					5: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "/OADate(44105)/", style: "__builtInStyle6"},
						2: {value: "/OADate(44196)/", style: "__builtInStyle6"},
						3: {value: 92, style: "__builtInStyle7"},
						4: {value: "Manufaturing", style: "__builtInStyle7"},
						5: {value: "Manufaturing\nPlant C", style: "__builtInStyle7"},
						6: {value: 2, style: "__builtInStyle7"},
						7: {value: "Camron\nWilliamon", style: "__builtInStyle7"},
						8: {value: 8538.16, style: "__builtInStyle7"},
						9: {value: 6314.001, style: "__builtInStyle7"},
						10: {value: 1906.2, style: "__builtInStyle7"},
						11: {value: "202012.pdf\nUpload New", style: "__builtInStyle8"},
					},
					6: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "/OADate(44105)/", style: "__builtInStyle6"},
						2: {value: "/OADate(44196)/", style: "__builtInStyle6"},
						3: {value: 92, style: "__builtInStyle7"},
						4: {value: "Manufaturing", style: "__builtInStyle7"},
						5: {value: "Manufaturing\nPlant C", style: "__builtInStyle7"},
						6: {value: 2, style: "__builtInStyle7"},
						7: {value: "Camron\nWilliamon", style: "__builtInStyle7"},
						8: {value: 8538.16, style: "__builtInStyle7"},
						9: {value: 6314.001, style: "__builtInStyle7"},
						10: {value: 1906.2, style: "__builtInStyle7"},
						11: {value: "202012.pdf\nUpload New", style: "__builtInStyle8"},
					},
					7: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "/OADate(44105)/", style: "__builtInStyle6"},
						2: {value: "/OADate(44196)/", style: "__builtInStyle6"},
						3: {value: 92, style: "__builtInStyle7"},
						4: {value: "Manufaturing", style: "__builtInStyle7"},
						5: {value: "Manufaturing\nPlant C", style: "__builtInStyle7"},
						6: {value: 2, style: "__builtInStyle7"},
						7: {value: "Camron\nWilliamon", style: "__builtInStyle7"},
						8: {value: 8538.16, style: "__builtInStyle7"},
						9: {value: 6314.001, style: "__builtInStyle7"},
						10: {value: 1906.2, style: "__builtInStyle7"},
						11: {value: "202012.pdf\nUpload New", style: "__builtInStyle8"},
					},
					8: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "/OADate(44105)/", style: "__builtInStyle6"},
						2: {value: "/OADate(44196)/", style: "__builtInStyle6"},
						3: {value: 92, style: "__builtInStyle7"},
						4: {value: "Manufaturing", style: "__builtInStyle7"},
						5: {value: "Manufaturing\nPlant C", style: "__builtInStyle7"},
						6: {value: 2, style: "__builtInStyle7"},
						7: {value: "Camron\nWilliamon", style: "__builtInStyle7"},
						8: {value: 8538.16, style: "__builtInStyle7"},
						9: {value: 6314.001, style: "__builtInStyle7"},
						10: {value: 1906.2, style: "__builtInStyle7"},
						11: {value: "202012.pdf\nUpload New", style: "__builtInStyle8"},
					},
					9: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "/OADate(44105)/", style: "__builtInStyle6"},
						2: {value: "/OADate(44196)/", style: "__builtInStyle6"},
						3: {value: 92, style: "__builtInStyle7"},
						4: {value: "Manufaturing", style: "__builtInStyle7"},
						5: {value: "Manufaturing\nPlant C", style: "__builtInStyle7"},
						6: {value: 2, style: "__builtInStyle7"},
						7: {value: "Camron\nWilliamon", style: "__builtInStyle7"},
						8: {value: 8538.16, style: "__builtInStyle7"},
						9: {value: 6314.001, style: "__builtInStyle7"},
						10: {value: 1906.2, style: "__builtInStyle7"},
						11: {value: "202012.pdf\nUpload New", style: "__builtInStyle8"},
					},
					10: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "/OADate(44105)/", style: "__builtInStyle6"},
						2: {value: "/OADate(44196)/", style: "__builtInStyle6"},
						3: {value: 92, style: "__builtInStyle7"},
						4: {value: "Manufaturing", style: "__builtInStyle7"},
						5: {value: "Manufaturing\nPlant C", style: "__builtInStyle7"},
						6: {value: 2, style: "__builtInStyle7"},
						7: {value: "Camron\nWilliamon", style: "__builtInStyle7"},
						8: {value: 8538.16, style: "__builtInStyle7"},
						9: {value: 6314.001, style: "__builtInStyle7"},
						10: {value: 1906.2, style: "__builtInStyle7"},
						11: {value: "202012.pdf\nUpload New", style: "__builtInStyle8"},
					},
					11: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "/OADate(44105)/", style: "__builtInStyle6"},
						2: {value: "/OADate(44196)/", style: "__builtInStyle6"},
						3: {value: 92, style: "__builtInStyle7"},
						4: {value: "Manufaturing", style: "__builtInStyle7"},
						5: {value: "Manufaturing\nPlant C", style: "__builtInStyle7"},
						6: {value: 2, style: "__builtInStyle7"},
						7: {value: "Camron\nWilliamon", style: "__builtInStyle7"},
						8: {value: 8538.16, style: "__builtInStyle7"},
						9: {value: 6314.001, style: "__builtInStyle7"},
						10: {value: 1906.2, style: "__builtInStyle7"},
						11: {value: "202012.pdf\nUpload New", style: "__builtInStyle8"},
					},
					12: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "/OADate(44105)/", style: "__builtInStyle6"},
						2: {value: "/OADate(44196)/", style: "__builtInStyle6"},
						3: {value: 92, style: "__builtInStyle7"},
						4: {value: "Manufaturing", style: "__builtInStyle7"},
						5: {value: "Manufaturing\nPlant C", style: "__builtInStyle7"},
						6: {value: 2, style: "__builtInStyle7"},
						7: {value: "Camron\nWilliamon", style: "__builtInStyle7"},
						8: {value: 8538.16, style: "__builtInStyle7"},
						9: {value: 6314.001, style: "__builtInStyle7"},
						10: {value: 1906.2, style: "__builtInStyle7"},
						11: {value: "202012.pdf\nUpload New", style: "__builtInStyle8"},
					},
					13: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "/OADate(44105)/", style: "__builtInStyle6"},
						2: {value: "/OADate(44196)/", style: "__builtInStyle6"},
						3: {value: 92, style: "__builtInStyle7"},
						4: {value: "Manufaturing", style: "__builtInStyle7"},
						5: {value: "Manufaturing\nPlant C", style: "__builtInStyle7"},
						6: {value: 2, style: "__builtInStyle7"},
						7: {value: "Camron\nWilliamon", style: "__builtInStyle7"},
						8: {value: 8538.16, style: "__builtInStyle7"},
						9: {value: 6314.001, style: "__builtInStyle7"},
						10: {value: 1906.2, style: "__builtInStyle7"},
						11: {value: "202012.pdf\nUpload New", style: "__builtInStyle8"},
					},
					14: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "/OADate(44105)/", style: "__builtInStyle6"},
						2: {value: "/OADate(44196)/", style: "__builtInStyle6"},
						3: {value: 92, style: "__builtInStyle7"},
						4: {value: "Manufaturing", style: "__builtInStyle7"},
						5: {value: "Manufaturing\nPlant C", style: "__builtInStyle7"},
						6: {value: 2, style: "__builtInStyle7"},
						7: {value: "Camron\nWilliamon", style: "__builtInStyle7"},
						8: {value: 8538.16, style: "__builtInStyle7"},
						9: {value: 6314.001, style: "__builtInStyle7"},
						10: {value: 1906.2, style: "__builtInStyle7"},
						11: {value: "202012.pdf\nUpload New", style: "__builtInStyle8"},
					},
					15: {
						0: {value: "", style: "__builtInStyle1"},
						1: {value: "/OADate(44105)/", style: "__builtInStyle6"},
						2: {value: "/OADate(44196)/", style: "__builtInStyle6"},
						3: {value: 92, style: "__builtInStyle7"},
						4: {value: "Manufaturing", style: "__builtInStyle7"},
						5: {value: "Manufaturing\nPlant C", style: "__builtInStyle7"},
						6: {value: 2, style: "__builtInStyle7"},
						7: {value: "Camron\nWilliamon", style: "__builtInStyle7"},
						8: {value: 8538.16, style: "__builtInStyle7"},
						9: {value: 6314.001, style: "__builtInStyle7"},
						10: {value: 1906.2, style: "__builtInStyle7"},
						11: {value: "202012.pdf\nUpload New", style: "__builtInStyle8"},
					},
				},
				defaultDataNode: {
					style: {
						font: "normal normal normal 11pt/normal Calibri",
						themeFont: "Body",
					},
				},
			},
			rowHeaderData: {defaultDataNode: {style: {themeFont: "Body"}}},
			colHeaderData: {defaultDataNode: {style: {themeFont: "Body"}}},
			rows: [
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
				{size: 48},
			],
			columns: [
				{size: 34},
				{size: 96},
				{size: 137},
				{size: 137},
				{size: 137},
				{size: 137},
				{size: 137},
				{size: 137},
				{size: 137},
				{size: 137},
				{size: 137},
				{size: 169},
			],
			defaultData: {},
			leftCellIndex: 0,
			topCellIndex: 0,
			selections: {0: {row: 0, col: 0, rowCount: 1, colCount: 1}, length: 1},
			defaults: {
				colHeaderRowHeight: 20,
				colWidth: 64,
				rowHeaderColWidth: 40,
				rowHeight: 20,
				_isExcelDefaultColumnWidth: true,
			},
			rowOutlines: {items: []},
			columnOutlines: {items: []},
			cellStates: {},
			states: {},
			outlineColumnOptions: {},
			autoMergeRangeInfos: [],
			shapeCollectionOption: {snapMode: 0},
			index: 0,
			order: 0,
		},
	},
	sheetTabCount: 0,
	namedStyles: [
		{
			backColor: null,
			foreColor: "#000000",
			hAlign: 3,
			vAlign: 2,
			font: "normal normal 14.6667px Calibri",
			themeFont: "Body",
			formatter: "General",
			borderLeft: null,
			borderTop: null,
			borderRight: null,
			borderBottom: null,
			locked: true,
			textIndent: 0,
			wordWrap: false,
			shrinkToFit: false,
			textDecoration: 0,
			name: "__builtInStyle0",
			isVerticalText: false,
			textOrientation: 0,
		},
		{
			backColor: null,
			foreColor: null,
			hAlign: 3,
			vAlign: 0,
			font: "normal normal 14.6667px Calibri",
			formatter: "General",
			borderLeft: {color: "#ffffff", style: 1},
			borderTop: {color: "#ffffff", style: 1},
			borderBottom: {color: "#ffffff", style: 1},
			locked: true,
			textIndent: 0,
			wordWrap: false,
			shrinkToFit: false,
			textDecoration: 0,
			name: "__builtInStyle1",
			isVerticalText: false,
			textOrientation: 0,
			applyFont: true,
			applyAlignment: true,
			applyBorder: true,
		},
		{
			backColor: null,
			foreColor: null,
			hAlign: 3,
			vAlign: 0,
			font: "normal normal 14.6667px Calibri",
			formatter: "General",
			borderLeft: {color: "#ffffff", style: 1},
			borderTop: {color: "#ffffff", style: 1},
			borderRight: {color: "#ffffff", style: 1},
			borderBottom: {color: "#ffffff", style: 1},
			locked: true,
			textIndent: 0,
			wordWrap: false,
			shrinkToFit: false,
			textDecoration: 0,
			name: "__builtInStyle2",
			isVerticalText: false,
			textOrientation: 0,
			applyFont: true,
			applyAlignment: true,
			applyBorder: true,
		},
		{
			backColor: null,
			foreColor: null,
			hAlign: 3,
			vAlign: 0,
			font: "normal normal 14.6667px Calibri",
			formatter: "General",
			borderLeft: {color: "#ffffff", style: 1},
			borderTop: {color: "#ffffff", style: 1},
			borderRight: {color: "#ffffff", style: 1},
			locked: true,
			textIndent: 0,
			wordWrap: false,
			shrinkToFit: false,
			textDecoration: 0,
			name: "__builtInStyle3",
			isVerticalText: false,
			textOrientation: 0,
			applyFont: true,
			applyAlignment: true,
			applyBorder: true,
		},
		{
			backColor: null,
			foreColor: null,
			hAlign: 1,
			vAlign: 1,
			font: "normal normal 14.6667px Calibri",
			formatter: "General",
			borderLeft: {color: "#ffffff", style: 1},
			borderTop: {color: "#ffffff", style: 1},
			borderBottom: {color: "#ffffff", style: 1},
			locked: true,
			textIndent: 0,
			wordWrap: true,
			shrinkToFit: false,
			textDecoration: 0,
			name: "__builtInStyle4",
			isVerticalText: false,
			textOrientation: 0,
			applyFont: true,
			applyAlignment: true,
			applyBorder: true,
		},
		{
			backColor: null,
			foreColor: null,
			hAlign: 1,
			vAlign: 1,
			font: "normal normal 14.6667px Calibri",
			formatter: "General",
			borderLeft: {color: "#ffffff", style: 1},
			borderTop: {color: "#ffffff", style: 1},
			borderRight: {color: "#ffffff", style: 1},
			borderBottom: {color: "#e7e6e6", style: 1},
			locked: true,
			textIndent: 0,
			wordWrap: true,
			shrinkToFit: false,
			textDecoration: 0,
			name: "__builtInStyle5",
			isVerticalText: false,
			textOrientation: 0,
			applyFont: true,
			applyAlignment: true,
			applyBorder: true,
		},
		{
			backColor: null,
			foreColor: null,
			hAlign: 1,
			vAlign: 1,
			font: "normal normal 14.6667px Calibri",
			formatter: "General",
			borderLeft: {color: "#ffffff", style: 1},
			borderRight: {color: "#ffffff", style: 1},
			borderBottom: {color: "#e7e6e6", style: 1},
			locked: true,
			textIndent: 0,
			wordWrap: true,
			shrinkToFit: false,
			textDecoration: 0,
			name: "__builtInStyle6",
			isVerticalText: false,
			textOrientation: 0,
			applyFont: true,
			applyAlignment: true,
			applyBorder: true,
		},
		{
			backColor: null,
			foreColor: null,
			hAlign: 1,
			vAlign: 1,
			font: "normal normal 14.6667px Calibri",
			formatter: "General",
			borderLeft: {color: "#ffffff", style: 1},
			borderRight: {color: "#ffffff", style: 1},
			borderBottom: {color: "#e7e6e6", style: 1},
			locked: true,
			textIndent: 0,
			wordWrap: true,
			shrinkToFit: false,
			textDecoration: 0,
			name: "__builtInStyle7",
			isVerticalText: false,
			textOrientation: 0,
			applyFont: true,
			applyAlignment: true,
			applyBorder: true,
		},
		{
			backColor: null,
			foreColor: "#8eacdb",
			hAlign: 1,
			vAlign: 1,
			font: "normal normal 14.6667px Calibri",
			formatter: "General",
			borderLeft: {color: "#ffffff", style: 1},
			borderRight: {color: "#ffffff", style: 1},
			borderBottom: {color: "#e7e6e6", style: 1},
			locked: true,
			textIndent: 0,
			wordWrap: true,
			shrinkToFit: false,
			textDecoration: 0,
			name: "__builtInStyle8",
			isVerticalText: false,
			textOrientation: 0,
			applyFont: true,
			applyAlignment: true,
			applyBorder: true,
		},
	],
	namedPatterns: {},
	pivotCaches: {},
};
window.onload = function () {
	var spread = new GC.Spread.Sheets.Workbook(document.getElementById("ss"), {
		sheetCount: 1,
	});
	initSpread(spread);
};

function initSpread(spread) {
	var sd = [dataJson];
	// var sd = data;
	console.log("xxx-----", data);
	if (sd.length > 0) {
		if (!spread) {
			return;
		}

		spread.suspendPaint();
		spread.fromJSON(sd[0]);
		// 在第一个表单中先插入5行
		const firstSheet = spread.getSheet(0);

		firstSheet.setColumnVisible(0, false, GC.Spread.Sheets.SheetArea.rowHeader); //隐藏行号
		firstSheet.setRowVisible(0, false, GC.Spread.Sheets.SheetArea.colHeader); //隐藏列号
		firstSheet.options.gridline = {
			showHorizontalGridline: false,
			showVerticalGridline: false,
		}; //水平线。垂直线

		firstSheet.addRows(0, 1); // 第一个参数是区域：0-内容区
		// 添加浮动元素-button
		addFloatButtonFunc(firstSheet);

		// 对浮动元素绑定事件
		bindEventForFloatButton(firstSheet);

		spread.resumePaint();
	}
}
// 添加浮动元素-button
function addFloatButtonFunc(sheet) {
	var spreadNS = GC.Spread.Sheets;
	var customFloatingObject = new spreadNS.FloatingObjects.FloatingObject(
		"f1",
		10,
		10,
		60,
		64
	);
	customFloatingObject.startRow(1);
	customFloatingObject.startColumn(3);
	customFloatingObject.endColumn(7);
	customFloatingObject.endRow(3);
	var div = document.createElement("div");
	div.id = "div";
	div.innerHTML =
		'<button id="addBtn" style="margin: 10px 30px;border: 1px solid;border-radius: 10px;background: #0FD59D;width: 80px;height: 36px;color:white;">新增</button> <button style="margin: 10px 30px;border: 1px solid;border-radius: 10px;background: #0FD59D;color:white;width: 80px;height: 36px;">编辑</button>';
	customFloatingObject.content(div);
	sheet.floatingObjects.add(customFloatingObject);
}
// 对浮动元素绑定事件
function bindEventForFloatButton(sheet) {
	var spreadNS = GC.Spread.Sheets;
	setTimeout(() => {
		var addBtn = document.getElementById("addBtn");
		// 为按钮绑定click事件处理函数
		addBtn.addEventListener("click", function () {
			alert("新增按钮被点击了!");
		});
	});
	sheet.bind(
		spreadNS.Events.FloatingObjectSelectionChanged,
		function (e, args) {
			console.log("FloatingObjectSelectionChanged-------", e, args);
		}
	);
	sheet.bind(spreadNS.Events.FloatingObjectChanged, function (e, args) {
		console.log("FloatingObjectChanged-------", e, args);
	});
}
